### ISSUE TITLE
Update it for `[uefi] version = "0.28.0"`

### ISSUE THREAD

**Issue by ghost** [theaddonn/uefi-graphics2#1]
This update nukes `uefi-services` crate, thus deprecating it. Instead, these functionalities are added to `uefi` as `features` and placed in `helpers` module. This is highly customizable. 

When i tried this with `[uefi] version = "0.28.0"`, i got incompatibility errors, like `FrameBuffer` is in version "0.28.0" but "0.27.0" is requested and same for `ModeInfo`. So i would like this to be ported to the newer version.

As mentioned in this project's `README.md`, other projects like `uefi-graphics` and `uefi-graphics-driver` seems to be heavily outdated. If possible, i would try to make a pull request for this change, as it is crucial for me to proceed further. I believe this project is still being maintained and not abandoned in 16 days

**Comment by Adrian8115** [comment]
`uefi-graphics2` is a newer and updated version that I maintain now... cuz this here wasn't touched in ages

**Comment by theaddonn** [comment]
Nope, this project is stil active... I'll try to test and update it in a couple of hours. Thanks for the issue!

**Comment by theaddonn** [comment]
I just published version `0.1.1`.. hopefully it solves your problems!

**Comment by theaddonn** [comment]
`0.1.3` is also now out and aims to fix a lot of problems and adds some more stuff

**Comment by ghost** [comment]
Yes, its now working as expected.
